### ISSUE TITLE
zoneminder 1.36.x + status returns 'Ok' not int()

### ISSUE THREAD

**Issue by ghost** [rohankapoorcom/zm-py#48]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 316, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 524, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/zoneminder/camera.py", line 57, in update
    self._is_recording = self._monitor.is_recording
  File "/usr/local/lib/python3.8/site-packages/zoneminder/monitor.py", line 169, in is_recording
    return status == STATE_ALARM
ValueError: invalid literal for int() with base 10: 'Ok'

**Comment by InkblotAdmirer** [comment]
I have a similar issue.  With cameras offline and set to "None" in Zoneminder the return value is "false" (which is also non-int).

As a test, I modified the area around line 169 in monitor.py:

```
        status = status_response.get("status")
        # ZoneMinder API returns an empty string to indicate that this monitor
        # cannot record right now
        if status == "":
            return False
        if status == "false":                                  <-- new line
            return False                                         <-- new line
        return int(status) == STATE_ALARM

```
The errors then go away.  This obviously isn't a recommendation, it's just testing that the Zoneminder API may be working differently than when this code was originally implemented.

**Comment by nabbi** [comment]
let's continue tracking this under #51
